GET  http://localhost:5000/user/users
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMTk1MWZhM2FjZWEzNDRmODQ2OTYzNCIsImlzQWRtaW4iOnRydWUsIm5hbWUiOiJhaG1hZHJlemFhYSIsImlhdCI6MTYyOTU3MTc4NiwiZXhwIjoxNjI5ODMwOTg2fQ.zEDC9kZXo396lu9qR5O6mJ8wJ-6naLlzN6ysYWhOKss

###
POST https://pizzland.herokuapp.com/user/register
Content-Type: application/json

{ 
     "name":"ahmad",
     "email":"ahmadrexs120@gmail.com",
     "password":"ahmadrexs120",
     "address":"sdfdsvgd"
     
}
###
POST https://pizzland.herokuapp.com/login
Content-Type: application/json

{ 
    
     "email":"ahmadrexs120@gmail.com",
     "password":"ahmadrexs120"
}
###

PUT  http://localhost:5000/user/update/611951fa3acea344f8469634
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMTk1MWZhM2FjZWEzNDRmODQ2OTYzNCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyOTEzNjA4NywiZXhwIjoxNjI5Mzk1Mjg3fQ.g7UGGvGJv2I_PirTfwKLnjY6YOMx9-4BXTHCj3mTN6s

{ 
     
     "curruntOrder":[{"orderId":"611ab1622caa35287c25584f","count":2}]
    
}
###
PUT  http://localhost:5000/user/moveToCartHistory/611951fa3acea344f8469634
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMTk1MWZhM2FjZWEzNDRmODQ2OTYzNCIsImlzQWRtaW4iOnRydWUsIm5hbWUiOiJhaG1hZHJlemFhYSIsImlhdCI6MTYyOTk2MzM5MywiZXhwIjoxNjMwMjIyNTkzfQ.uXb0E-L3mKNQ3c3t_ZGf7vsgeq6MhpoUXzj59ZRZV1w


###

POST http://localhost:5000/foods/newFood
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMTk1MWZhM2FjZWEzNDRmODQ2OTYzNCIsImlzQWRtaW4iOnRydWUsIm5hbWUiOiJhaG1hZHJlemFhYSIsImlhdCI6MTYyOTc0MTU2MywiZXhwIjoxNjMwMDAwNzYzfQ.rFCfXanbpHgwpi74SlbJ2JwFQCJZ4DFmDLAcgDLIRXI

{ 
     "type":"fastFood",
     "name":"peperoni pizza",
     "pic":"https://previews.123rf.com/images/danilsneg/danilsneg1706/danilsneg170600158/81077084-peperoni-pizza-italienische-pizza-auf-wei%C3%9Fem-hintergrund-.jpg",
     "price":12,
     "madeFrom":"cheese,onion,meat,peperoni,chicken"
     
}
###
###

GET  https://pizzland.herokuapp.com/foods
Content-Type: application/json


###
PUT  http://localhost:5000/foods/rate/611ab1622caa35287c25584f
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMTk1MWZhM2FjZWEzNDRmODQ2OTYzNCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyOTEzNjA4NywiZXhwIjoxNjI5Mzk1Mjg3fQ.g7UGGvGJv2I_PirTfwKLnjY6YOMx9-4BXTHCj3mTN6s

{ 
    "rate":4
}
###
PUT  http://localhost:5000/foods/comment/611ab1622caa35287c25584f
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMTk1MWZhM2FjZWEzNDRmODQ2OTYzNCIsImlzQWRtaW4iOnRydWUsIm5hbWUiOiJhaG1hZHJlemFhYSIsImlhdCI6MTYyOTIyMTU4NSwiZXhwIjoxNjI5NDgwNzg1fQ.LKPaDwnde6nj3-OIsLBOpY551C6ak0MA7jkeiylRamg

{ 
    "comment":"very very delicios,thank u pizzaStore"
}
###
DELETE   http://localhost:5000/foods/deleteComment/611ab1622caa35287c25584f
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMTk1MWZhM2FjZWEzNDRmODQ2OTYzNCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyOTEzNjA4NywiZXhwIjoxNjI5Mzk1Mjg3fQ.g7UGGvGJv2I_PirTfwKLnjY6YOMx9-4BXTHCj3mTN6s

{ 
    "id":"611951fa3acea344f8469634"
}
###
DELETE   http://localhost:5000/user/deleteAccount/611a71e6cffac41b8439b85d
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMWE3MWU2Y2ZmYWM0MWI4NDM5Yjg1ZCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjkxMjMyMzQsImV4cCI6MTYyOTM4MjQzNH0.0LXWolVskWuH32qJr5vp0EdAAW7ddcE_QH4rumVzd6Q